### ISSUE TITLE
Fix inconsistent naming

### ISSUE THREAD

**Issue by Restuta** [JuniLearning/eslint-config-juni#3]
The project / repo name is "juni-eslint-config" while package name is "eslint-config-juni", I suggest renaming one or the other to keep it consistent.

I would suggest to rename the repo, as package is named similar to others like https://www.npmjs.com/package/eslint-config-airbnb

**Comment by tristan-kenneth-tarpley** [comment]
Right. Eslint actually relies on the eslint-config-*package name* naming convention, so we'll have to make it eslint-config-juni across the board. Will do.
